### ISSUE TITLE
About pretrained model

### ISSUE THREAD

**Issue by cats-food** [ZongyuGuo/Inpainting_FRRN#6]
First of all, thank you for your great work and your code contribution : )
I have a question about your pretrained model provided in the directory `save_models`:
I wonder which dataset did this model train on? CelebA, Places2 or Paris Street View?
Also, if this is trained on either dataset, could you please share the others (if it is possible). my email address is yangshiyuan@tju.edu.cn.
I'm looking forward to your reply, thank you very much.

**Comment by ZongyuGuo** [comment]
Since this repo was built two years ago, if I remember correctly, this pre-trained model is optimized on the full training set of Places2, without any other images exactly.

**Comment by cats-food** [comment]
Wow, thanks for your quick reply! May I ask for the model pretrained on CelebA, if you still keep that

**Comment by ZongyuGuo** [comment]
I checked my server carefully but eventually cannot find the pre-trained model of CelebA. Sorry for that. But you can train the model from the beginning by yourself since the training process on CelebA does not take a long time.

**Comment by cats-food** [comment]
It's ok~  I am so grateful for your kind help 👍
